version: '2.1'
services:
  zeppelin:
    labels:
      - "project=PortalDB"
    image: portaldb/zeppelin:latest
    ports:
      - "8080:8080"
    volumes:
      - zeppelinnotebook:/zeppelin/notebook
      - zeppelinconf:/zeppelin/conf

volumes:
    zeppelinnotebook:
        driver: local
        labels:
            - "project=tgraph"
            - "service=zeppelin"
    zeppelinconf:
        driver: local
        labels:
            - "project=tgraph"
            - "service=zeppelin"